# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ignacio Sanmillan
email: n4x0r@amn3s1a.com
description: > # this means to ignore newlines until "baseurl:"
        Computer Science Student, Reverse Engineer and CTF player with amn3s1a_t3am
baseurl: "" 
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: @n4x0r_
github_username:  n4x0r

# Build settings
markdown: kramdown
