# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
future: true
title: Ignacio Sanmillan's Blog
email: n4x0r@amn3s1a.com
description: > # this means to ignore newlines until "baseurl:"
        Reverse Engineer and Exploit Development Hobbyst. Unix enthutiast. Breaking new things everyday.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://n4x0r.github.io" # the base hostname & protocol for your site
twitter_username: n4x0r_
github_username:  n4x0r
theme: minima
# Build settings
markdown: kramdown
