# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bona Fides
description: ulexec's blog
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://ulexec.github.io"
twitter_username: ulexec
github_username:  ulexec
telegram_username: ulexec
ctftime_id: 8210
recent_posts: 5
future: true

# Build settings
theme: jekyll-theme-time-machine
markdown: kramdown
highlighter: rouge
# Menus de navegacion
navigation:
- text: Home
  url: /
- text: Malware
  url: /malware/
- text: CTF
  url: /writeups/
  layout: writeup
- text: CTI
  url: /cti/
- text: Misc
  url: /misc/
- text: Talks
  url: /videos/
- text: Projects
  url: /projects/
