# Welcome to my Blog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ignacio Sanmillan Blog
email: n4x0r@amn3s1a.com
description: > # this means to ignore newlines until "baseurl:"
  Computer Scientist, Reverse Engineering and CTF player. This blog will hold writeups of research, competitions
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://n4x0r.github.io" # the base hostname & protocol for your site
twitter_username: n4x0r_
github_username:  n4x0r

# Build settings
markdown: kramdown
